### ISSUE TITLE
Assets directory not found in the deploy branch

### ISSUE THREAD

**Issue by bhi5hmaraj** [pengx17/knowledge-garden#6]
I'm using the following action, but I don't see an `asset` folder in my `gh-pages` branch. I tried generating it in a new branch and faced the same issue over there too. Am I missing something? 

```
# This is a basic workflow to help you get started with Actions
# Taken from https://github.com/pengx17/logseq-publish

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@main
        with:
          version: "master"
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-new # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
          single-commit: true
```
